# YouTube2DiscordLink (formerly YTSCTD) 2.0.0
# Config File
# For smooth operation, follow the instructions at https://jbcarreon123.github.io/docs/y2dl

# DO NOT TOUCH THIS!
Version: 2.0.0-b1

Main:
  # Webhook or Bot
  Type: Bot

  # If bot, configure this.
  # If not, don't touch this.
  BotConfig: 
    BotToken: MTE0MTkxOTE2NjI0OTU4MjYxMg.G70ewH.3njMI1nyQm0xlaUA-igucuAtDcsXftog2l6GDk
    State: DoNotDisturb
    Status:
      Enabled: true
      Emoji: 🔗
      Text: github.com/jbcarreon123/y2dl

  WebhookConfig:
    Name: Y2DL Relay Webhook
    AvatarUrl: https://jbcarreon123.github.io/Y2DL.png

  # The update interval (in milliseconds)
  UpdateInterval: 300000

  # Required at least 1 so it can get the info.
  ApiKeys:
    - YoutubeApiKey: AIzaSyASdxROAYSoJhQljVGXU9DbgXtVliHkBYY
      YoutubeApiName: ApiGet

  # Defines the log severity to shown in the console.
  Logging:
    LogLevel: Verbose
    LogErrorChannel:
      UseWebhook: true
      WebhookUrl: https://discord.com/api/webhooks/1146787365499707412/c1B23koSLljd8Y9IDMpFwF_YoAp3iS5TrUTxqfj9nYRuWXA4zWPwDodSqS93FYebuvEd
      GuildId: 1135815464891732089
      ChannelId: 1146787335799836682

Services:
  DynamicChannelInfo:
    Enabled: true
    # Supports the full Discord Markdown (for Bots/Webhooks).
    # {channel} for Channel Name, and {channelUrl} for channel's URL
    # {lVidName} for latest video's title, {lVidThumbnail} for it's thumbnail,
    # and {lVidUrl} for it's URL
    # Go to https://jbcarreon123.github.io/docs/y2dl/message for more variables.
    Messages:
      - ChannelId: UCrfSLDt8FxdIpHpukEjqgdw
        Output: 
          # If you want to use a webhook instead of a bot, without using Webhook mode, set this to true.
          # Note: Only used in Bot mode. If in Webhook mode, it is ignored because you already using a webhook.
          UseWebhook: false
          # The 2 things below is only used in Bot mode.
          GuildId: 1135815464891732089
          ChannelId: 1135820971249516617
        Embed:
          Title: "{Name} ({Handle})"
          TitleUrl: "{ChannelUrl}"
          Description: |
            {Description}
            Subscribers: **{Statistics.Subscribers}**
          Color: "#ff0000"
          ImageUrl: "{LatestVideo.Thumbnail}"
          ThumbnailUrl: "{ChannelAvatarUrl}"
          Fields:
            - Name: "Latest video"
              Value: |
                **[{LatestVideo.Title}]({LatestVideo.Url})**
                Views: **{LatestVideo.Statistics.Views}**
                Likes: **{LatestVideo.Statistics.Likes}**
                Comments: **{LatestVideo.Statistics.Comments}**
      - ChannelId: UCwB-OyKbjbK1bj3Lr9NZgNQ
        Output: 
          # If you want to use a webhook instead of a bot, without using Webhook mode, set this to true.
          # Note: Only used in Bot mode. If in Webhook mode, it is ignored because you already using a webhook.
          UseWebhook: false
          # The 2 things below is only used in Bot mode.
          GuildId: 1080361344542445588
          ChannelId: 1146985373935874118
        Embed:
          Title: "{Name} ({Handle})"
          TitleUrl: "{ChannelUrl}"
          Description: |
            {Description}
            Subscribers: **{Statistics.Subscribers}**
          Color: "#ff0000"
          ImageUrl: "{LatestVideo.Thumbnail}"
          ThumbnailUrl: "{ChannelAvatarUrl}"
          Fields:
            - Name: "Latest video"
              Value: |
                **[{LatestVideo.Title}]({LatestVideo.Url})**
                Views: **{LatestVideo.Statistics.Views}**
                Likes: **{LatestVideo.Statistics.Likes}**
                Comments: **{LatestVideo.Statistics.Comments}**
      - ChannelId: UCtd-qJN3ilLJpZky8pf63zQ
        Output: 
          # If you want to use a webhook instead of a bot, without using Webhook mode, set this to true.
          # Note: Only used in Bot mode. If in Webhook mode, it is ignored because you already using a webhook.
          UseWebhook: false
          # The 2 things below is only used in Bot mode.
          GuildId: 1080361344542445588
          ChannelId: 1146985373935874118
        Embed:
          Title: "{Name} ({Handle})"
          TitleUrl: "{ChannelUrl}"
          Description: |
            {Description}
            Subscribers: **{Statistics.Subscribers}**
          Color: "#ff0000"
          ImageUrl: "{LatestVideo.Thumbnail}"
          ThumbnailUrl: "{ChannelAvatarUrl}"
          Fields:
            - Name: "Latest video"
              Value: |
                **[{LatestVideo.Title}]({LatestVideo.Url})**
                Views: **{LatestVideo.Statistics.Views}**
                Likes: **{LatestVideo.Statistics.Likes}**
                Comments: **{LatestVideo.Statistics.Comments}**


  ChannelReleases:
    Enabled: true
    # Supports the full Discord Markdown (for Bots/Webhooks).
    # {channel} for Channel Name, and {channelUrl} for channel's URL
    # {lVidName} for latest video's title, {lVidThumbnail} for it's thumbnail,
    # and {lVidUrl} for it's URL
    # Go to https://jbcarreon123.github.io/docs/y2dl/message for more variables.
    Messages:
      - ChannelId: UCrfSLDt8FxdIpHpukEjqgdw
        Output: 
          # If you want to use a webhook instead of a bot, without using Webhook mode, set this to true.
          UseWebhook: false
          # Only used in Webhook mode, or if you set UseWebhook to true.
          WebhookUrl: YOUR_DISCORD_WEBHOOK_URL
          # The 2 things below is only used in Bot mode.
          GuildId: 1135815464891732089
          ChannelId: 1135820971249516617
        Content: "<@1135817265292525648>"
        Embed:
          Author: "New video on {Name} is just released!"
          Title: "{LatestVideo.Title}"
          TitleUrl: "{LatestVideo.Url}"
          Description: "{LatestVideo.Description}"
          Color: "#252525"
          ImageUrl: "{LatestVideo.Thumbnail}"
      - ChannelId: UCwB-OyKbjbK1bj3Lr9NZgNQ
        Output: 
          # If you want to use a webhook instead of a bot, without using Webhook mode, set this to true.
          UseWebhook: false
          # Only used in Webhook mode, or if you set UseWebhook to true.
          WebhookUrl: YOUR_DISCORD_WEBHOOK_URL
          # The 2 things below is only used in Bot mode.
          GuildId: 1080361344542445588
          ChannelId: 1140267420011986954
        Content: "<@1145486958286614679>"
        Embed:
          Author: "New video on {Name} is just released!"
          Title: "{LatestVideo.Title}"
          TitleUrl: "{LatestVideo.Url}"
          Description: "{LatestVideo.Description}"
          Color: "#252525"
          ImageUrl: "{LatestVideo.Thumbnail}"
      - ChannelId: UCtd-qJN3ilLJpZky8pf63zQ
        Output: 
          # If you want to use a webhook instead of a bot, without using Webhook mode, set this to true.
          UseWebhook: false
          # Only used in Webhook mode, or if you set UseWebhook to true.
          WebhookUrl: YOUR_DISCORD_WEBHOOK_URL
          # The 2 things below is only used in Bot mode.
          GuildId: 1080361344542445588
          ChannelId: 1140267420011986954
        Content: "<@1145486958286614679>"
        Embed:
          Author: "New video on {Name} is just released!"
          Title: "{LatestVideo.Title}"
          TitleUrl: "{LatestVideo.Url}"
          Description: "{LatestVideo.Description}"
          Color: "#252525"
          ImageUrl: "{LatestVideo.Thumbnail}"

  # Only works if Type is Bot. Else, it will be ignored.
  DynamicChannelInfoForVoiceChannels:  
    Enabled: true
    # {channel} for Channel Name, and {channelSubscribers} for subscibers.
    # Go to https://jbcarreon123.github.io/docs/y2dl/voicechannels for more variables.
    Channels:
      - ChannelId: UCrfSLDt8FxdIpHpukEjqgdw
        VoiceChannels:
          - GuildId: 1135815464891732089
            ChannelId: 1146790397713059981
            Name: "{Statistics.FormattedSubscribers} subscribers"
          - GuildId: 1135815464891732089
            ChannelId: 1146790428872540240
            Name: "{Statistics.FormattedVideos} videos"
          - GuildId: 1135815464891732089
            ChannelId: 1146790461378412595
            Name: "{Statistics.FormattedViews} views"
      - ChannelId: UCwB-OyKbjbK1bj3Lr9NZgNQ
        VoiceChannels:
          - GuildId: 1080361344542445588
            ChannelId: 1146983921955897474
            Name: "Subscribers: {Statistics.FormattedSubscribers}"
          - GuildId: 1080361344542445588
            ChannelId: 1146985220889907271
            Name: "Videos: {Statistics.FormattedVideos}"
          - GuildId: 1080361344542445588
            ChannelId: 1146985295196196905
            Name: "Views: {Statistics.FormattedViews}"
      - ChannelId: UCtd-qJN3ilLJpZky8pf63zQ
        VoiceChannels:
          - GuildId: 1080361344542445588
            ChannelId: 1146985906859941888
            Name: " _Zacronium: {Statistics.FormattedSubscribers}"
          

  # Only works if Type is Bot. Else, it will be ignored.
  Commands:
    Enabled: true
    # Available types: SlashCommand, Prefix, or Both.
    Type: Both
    # Only used if Type is Prefix or Both.
    Prefix: "!"
    About:
      Enabled: true
      Embed:
        Author: "{Name}"
        AuthorAvatarUrl: "{AvatarUrl}"
        Fields:
          - Name: "Bot Owner"
            Value: "<@908002848967626842>"